### ISSUE TITLE
Can't deploy

### ISSUE THREAD

**Issue by rossdakin** [presidential-innovation-fellows/pif-website#90]
Getting the same error @stroupaloop got a while ago:

```zsh
~/Code/pif-website$ s3_website push
[info] Deploying /Users/rossdakin/Code/pif-website/_site/* to presidentialinnovationfellows.gov
Exception in thread "pool-1-thread-13" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at scala.collection.mutable.ListBuffer.$plus$eq(ListBuffer.scala:174)
	at scala.collection.mutable.ListBuffer.$plus$eq(ListBuffer.scala:45)
	at scala.collection.generic.Growable$class.loop$1(Growable.scala:53)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:57)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.TraversableLike$class.$plus$plus(TraversableLike.scala:157)
	at scala.collection.immutable.List.$plus$plus(List.scala:196)
	at s3.website.S3$$anonfun$resolveS3Files$2.apply(S3.scala:140)
	at s3.website.S3$$anonfun$resolveS3Files$2.apply(S3.scala:132)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by stroupaloop** [comment]
moving off of s3_website gem and using cloud.gov moving forward
